stages:
  - cml_run

cml:
  stage: cml_run
  image: iterativeai/cml:0-dvc2-base1
  script:
    - dvc pull data

    - pip install -r requirements.txt
    - dvc repro

#    # Compare metrics to master
#    - git fetch --prune
#    - dvc metrics diff --show-md master >> report.md
#
#    # Visualize loss function diff
#    - dvc plots diff
#      --target loss.csv --show-vega master > vega.json
#    - vl2png vega.json > plot.png
#    - cml publish --md plot.png >> report.md
#    - cml send-comment report.md
#